services:
  jobrythm-api:
    image: jobrythm-api:latest
    build:
      context: .
      dockerfile: src/Jobrythm.Api/Dockerfile
    container_name: jobrythm-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=jobrythm-db;Database=jobrythm;Username=postgres;Password=postgres
      - JwtSettings__Secret=A_VERY_SECRET_KEY_THAT_IS_LONG_ENOUGH_FOR_HMACSHA256
      - JwtSettings__ValidIssuers__0=https://api.jobrythm.com
      - JwtSettings__ValidIssuers__1=https://api.jobrythm.aricummings.com
      - JwtSettings__ValidAudiences__0=https://app.jobrythm.com
      - JwtSettings__ValidAudiences__1=https://app.jobrythm.aricummings.com
      - AppConfig__BaseUrls__0=https://api.jobrythm.com
      - AppConfig__BaseUrls__1=https://api.jobrythm.aricummings.com
      - AppConfig__ClientUrls__0=http://localhost:5173
      - AppConfig__ClientUrls__1=https://app.jobrythm.com
      - AppConfig__ClientUrls__2=https://app.jobrythm.aricummings.com
    depends_on:
      jobrythm-db:
        condition: service_healthy
    restart: always

  jobrythm-db:
    image: postgres:17-alpine
    container_name: jobrythm-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jobrythm
    ports:
      - "5432:5432"
    volumes:
      - jobrythm-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jobrythm"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: jobrythm-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@jobrythm.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - jobrythm-db
    restart: always

volumes:
  jobrythm-db-data:
